- name: Gather and print local facts
  hosts: localhost
  become: true
  gather_facts: true
  tasks:

   - name: Print facts
     ansible.builtin.debug:
      msg:
        - "Facts says hostname is: {{ ansible_facts.hostname }}"
        - "Facts says the host distribution is: {{ ansible_facts.distribution }}"

   - name: Lazy get collection information
     ansible.builtin.shell: ansible-galaxy collection list
     register: result

   - name: Print return information from the previous task
     ansible.builtin.debug:
      var: result.stdout_lines[2:6]